### ISSUE TITLE
decide on backend framework

### ISSUE THREAD

**Issue by natestemen** [natestemen/mathdb#2]
do we want Ruby on Rails, node, elixir, something else?

**Comment by Shearyar** [comment]
Python with django but we can do Ruby on Rails since it has support. I'm up for anything.

**Comment by natestemen** [comment]
rails does have a very large user base. it would mean a bit of a slower upstart since you'll be learning ruby at the same time as rails.

I don't know anything about Django, but we are both pretty familiar with python.

I think ruby is better suited for the job. okay with that?

**Comment by Shearyar** [comment]
I'll go read up on Ruby on Rails. I'm not that familiar with Django either.
In the meantime we can gather more texts.

**Comment by natestemen** [comment]
Cool. Since it looks like we'll go with rails ill close this ticket out.
